version: "3"
services:
  curator_nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}_cdcs_nginx
    restart: always
    ports:
      - "${NGINX_PORT_80}:80"
      - "${NGINX_PORT_443}:443"
    depends_on:
      - cdcs
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - cdcs_socket:/tmp/curator/
      - cdcs_static:/srv/curator_static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/${SERVER_CONF}.conf:/etc/nginx/templates/default.conf.template
  curator_postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${PROJECT_NAME}_cdcs_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
  curator_redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}_cdcs_redis
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    volumes:
      - redis_data:/data
  cdcs:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${PROJECT_NAME}_cdcs
    restart: always
    depends_on:
      - curator_redis
      - curator_postgres
    volumes:
      - cdcs_media:/srv/curator/media
      - cdcs_socket:/tmp/curator/
      - cdcs_static:/srv/curator/static.prod
      # Uncomment to mount additional settings file
#      - ./cdcs/${SETTINGS}.py:/srv/curator/${PROJECT_NAME}/${SETTINGS}.py
    environment:
      - DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.${SETTINGS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SERVER_URI=${SERVER_URI}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SERVER_NAME=${SERVER_NAME:-}
      - MONGO_HOST=${PROJECT_NAME}_cdcs_mongo
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - POSTGRES_HOST=${PROJECT_NAME}_cdcs_postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - REDIS_HOST=${PROJECT_NAME}_cdcs_redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASS=${REDIS_PASS}
    env_file:
      - ./saml2/.env
      - ./handle/.env
      - ./extra/.env
    command:
      - ${PROJECT_NAME}
      - ${WEB_SERVER:-uwsgi}

volumes:
  postgres_data:
  redis_data:
  cdcs_media:
  cdcs_socket:
  cdcs_static:
