version: "3"
services:
  celery_beat:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${PROJECT_NAME}_celery_beat
    restart: always
    depends_on:
      - curator_redis
      - curator_postgres
      - cdcs
    # Uncomment to mount additional settings file
#    volumes:
#      - ./cdcs/${SETTINGS}.py:/srv/curator/${PROJECT_NAME}/${SETTINGS}.py
    environment:
      - DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.${SETTINGS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SERVER_URI=${SERVER_URI}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SERVER_NAME=${SERVER_NAME:-}
      - MONGO_HOST=${PROJECT_NAME}_cdcs_mongo
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - POSTGRES_HOST=${PROJECT_NAME}_cdcs_postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - REDIS_HOST=${PROJECT_NAME}_cdcs_redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASS=${REDIS_PASS}
    entrypoint: /docker-entrypoint-celery-beat.sh
    command:
      - ${PROJECT_NAME}
    env_file:
      - ./extra/.env

  celery_worker:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${PROJECT_NAME}_celery_worker
    restart: always
    depends_on:
      - curator_redis
      - curator_postgres
      - cdcs
    # Uncomment to mount additional settings file
#    volumes:
#      - ./cdcs/${SETTINGS}.py:/srv/curator/${PROJECT_NAME}/${SETTINGS}.py
    environment:
      - DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.${SETTINGS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SERVER_URI=${SERVER_URI}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SERVER_NAME=${SERVER_NAME:-}
      - MONGO_HOST=${PROJECT_NAME}_cdcs_mongo
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - POSTGRES_HOST=${PROJECT_NAME}_cdcs_postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - REDIS_HOST=${PROJECT_NAME}_cdcs_redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASS=${REDIS_PASS}
    entrypoint: /docker-entrypoint-celery-worker.sh
    command:
      - ${PROJECT_NAME}
    env_file:
      - ./extra/.env